
.PHONY: all clean

all: Question_1 Question_2 Question_3 Question_4
	make -C Question_1 all
	make -C Question_2 all
	make -C Question_3 all
	make -C Question_4 all

clean:
	make -C Question_1 clean
	make -C Question_2 clean
	make -C Question_3 clean
	make -C Question_4 clean
